### ISSUE TITLE
Not working since yesterday 

### ISSUE THREAD

**Issue by pratikaisle3** [foo-software/lighthouse-check-action#75] opened 2022-01-06 11:05 UTC
Run foo-software/lighthouse-check-action@master
  with:
    urls: https://idevops.tech
    slackWebhookUrl: ***
    device: desktop,mobile
  env:
    SLACK_WEBHOOK_URL: ***
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
lighthouse-check: Auditing desktop,mobile (1/1): https://idevops.tech
lighthouse-check:
 TypeError: Cannot read properties of undefined (reading 'settings')
    at localLighthouse (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:54:44)
    at getLocalLighthouseResultsWithRetries (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:124:35)
    at _default (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:***9:41)
    at /home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/lighthouseCheck.js:175:67
    at new Promise (<anonymous>)
    at _default (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/lighthouseCheck.js:69:7)
    at /home/runner/work/_actions/foo-software/lighthouse-check-action/master/dist/index.js:65:70
    at Object.<anonymous> (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/dist/index.js:104:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Error: Cannot read properties of undefined (reading 'settings')

**Comment by adamhenson** [comment] 2022-01-06 11:41
@pratikaisle3 please provide a way to reproduce or your approximate configuration.

**Comment by adamhenson** [comment] 2022-01-06 17:11
Cannot reproduce. This action seems to be working normally (screenshot below). Without a provided reproduction, no action can be taken, hence closing. If the problem persists, please open a new issue and fill use the new issue template.

<img width="960" alt="Screen Shot 2022-01-06 at 12 01 53 PM" src="https://user-images.githubusercontent.com/747743/148422346-b9d59e3c-fc35-4fc0-8f0c-20ce98a9eba8.png">

**Closed by adamhenson** 2022-01-06 17:11 UTC
Labels: incomplete issue
