### ISSUE TITLE
Lighthouse verification step passes with error

### ISSUE THREAD

**Issue by marklaatikainen** [foo-software/lighthouse-check-action#99] opened 2022-07-13 07:39 UTC
**Describe the bug**
Step passes with runtime error

**To Reproduce**
Run check against url that loads slowly

**Expected behavior**
Step should fail if page could not load

**Additional context**
Our webstore preview link takes long time to load on first load after it was built. Step passes still with SUCCESS when it has `runtimeError`

```
lighthouseCheckResults: {"code":"SUCCESS","data":[{"url":"webstore-preview-url","emulatedFormFactor":"desktop","runtimeError":"The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP)","scores":{}}]}
```

**Actual result**
lighthouse-check: Scores passed minimum requirement ✅

**Comment by adamhenson** [comment] 2022-07-13 11:37
@marklaatikainen - could you please update this issue to provide more details in the "To Reproduce" section and "Expected behavior" section? It looks like you provided the output of the GitHub Action which looks correct.

Please provide your configuration or some similar example configuration. I would expect there to be no scores in the output and an error message per [this recent PR](https://github.com/foo-software/lighthouse-check/pull/67). Do you not see an error message in the output?

**Is the problem that you are [using `foo-software/lighthouse-check-status-action`](https://www.foo.software/docs/lighthouse-check-github-action/examples#failing-workflows-by-enforcing-minimum-scores) and the workflow doesn't fail when you would expect it to?** If so, you would definitely need to at least specify the relevant configuration for that (it's actually a different GitHub Action altogether... but it is related to this, so we can keep this open).

Regardless, I will need a minimal example and more information to understand the issue better.

**Comment by marklaatikainen** [comment] 2022-07-13 12:01
<img width="761" alt="image" src="https://user-images.githubusercontent.com/22056390/178727435-7f325a7f-4893-467f-818b-56fa6dbab7f9.png">

Configuration looks like this. There are separate jobs for desktop and mobile, with different minimum scores. 

It gives following output and passes both steps:

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/22056390/178728408-9c785683-6ee2-49cd-b0ec-3a8addabb583.png">

**Comment by adamhenson** [comment] 2022-07-13 12:04
I see... thank you @marklaatikainen. As I suspected - this GitHub Action is actually working as expected. The issue resides in [lighthouse-check-status-action](https://github.com/foo-software/lighthouse-check-status-action), which is a different repo altogether.

Let's keep this open here since the other repo isn't well known. I'm busy today and tomorrow, but should be able to get to the bottom of it on Friday.

**Comment by adamhenson** [comment] 2022-07-15 00:23
@marklaatikainen thanks again for opening this issue. It has been resolved and released in [foo-software/lighthouse-check-action@9.0.0](https://github.com/foo-software/lighthouse-check-action/releases/tag/v9.0.0).

We now "fast fail" a job when a runtime error occurs. [Example](https://github.com/foo-software/lighthouse-check-action/runs/7349896979?check_suite_focus=true)

Closing this, but feel free to comment or re-open if needed.

**Closed by adamhenson** 2022-07-15 00:23 UTC
Labels: bug, in progress

**Comment by marklaatikainen** [comment] 2022-07-15 04:12
Thank you for quick fix 👍 Seems to be working now. @adamhenson

**Comment by adamhenson** [comment] 2022-07-15 04:15
👍
