### ISSUE TITLE
Is api token required?

### ISSUE THREAD

**Issue by Vadorequest** [foo-software/lighthouse-check-action#24] opened 2020-05-25 18:02 UTC
It's not clear from the doc if the LightHouse API token is required, or if it's useful to link the result to a particular account.

Also, is it sensitive? Because my goal is to use it in an OSS project and I wonder if I need to protect it using GitHub secrets or if I can just use it in clear text.

**Comment by adamhenson** [comment] 2020-05-31 20:22
Hi @Vadorequest - sorry for the confusion. This project provides two ways of running audits - "locally" by default in a dockerized GitHub environment or remotely via Automated Lighthouse Check API. For basic usage, running locally will suffice, but if you'd like to maintain a historical record of Lighthouse audits and utilize other features, running remotely is a better option.

**You only need the an API token if you're running audits remotely**. This project has become a bit bloated in documentation and functionality which is mainly caused by these two distinct ways of using the GitHub Action. The plan is split it into two in the future, without introducing breaking changes. The documentation will be revamped during this process.

In regards to sensitivity, the API token holds the same level of sensitivity as any API account specific token you might manage. The way you protect it is up to you.

Does this answer your questions?

**Comment by Vadorequest** [comment] 2020-05-31 22:17
Thanks Adam!

Yes, it helps. I believe I must treat this API token as securely as possible. 

(some API tokens are actually public, like analytics/monitoring API where you just send data using a public api token, that was the actual underlying concern)

So, the most simple use case for me would be to run it as CI Github Action without API "locally" on the CI server, without history. 

And use the "comment" feature to write the result once Lighthouse has run.

Do I get it right? 😄

**Comment by adamhenson** [comment] 2020-05-31 22:25
No problem @Vadorequest. Yes, that's correct. In your case - you shouldn't need a Lighthouse specific `apiToken`, but to use commenting on PRs you'll need [`accessToken` which you may have already read about in the docs](https://github.com/foo-software/lighthouse-check-action#inputs). I'm closing this for now, but feel free to ask any more questions or comment here and I'll respond.

**Closed by adamhenson** 2020-05-31 22:25 UTC
Labels: question
