### ISSUE TITLE
Report link does not show up on Pull Request

### ISSUE THREAD

**Issue by emperol2** [foo-software/lighthouse-check-action#92] opened 2022-05-10 10:22 UTC
**Describe the bug**

The Report link does not show up on Pull Request. This might not be a bug but I might misunderstand something.

**To Reproduce**

![image](https://user-images.githubusercontent.com/531184/167606917-d735d9cf-be25-4986-81a3-4a1f16ae8409.png)

![image](https://user-images.githubusercontent.com/531184/167607324-a6f4a86c-109e-4457-907f-866ceb8cafbb.png)

**Expected behavior**

The report link should show on the table.

**Additional context**

N/A

Thank you very much 🙇

**Comment by adamhenson** [comment] 2022-05-10 11:46
Hello - @emperol2. With this basic configuration there isn't anything to link to. GitHub Artifacts are temporary and even if there was a way to link to them (which I don't think would be straightforward), it wouldn't be sensible based on their ephemeral nature.

To have links show in PRs you have 2 options:

1. Establish [AWS service and create an S3 bucket](https://aws.amazon.com/pm/serv-s3) if you don't have one and follow the [example here to add S3 creds](https://www.foo.software/docs/lighthouse-check-github-action/examples#save-html-reports-to-aws-s3-slack-notifications-and-pr-comments).
2. [Sign up and integrate with Foo](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results), so that all results are saved on Foo (to provide a historical timeline). Note in the linked example, you can add respective inputs to get PR comments.

You are correct that this is not a bug and is expected behavior, hence closing. Feel free to confirm the above solution or ask me additional questions here as comments.

**Closed by adamhenson** 2022-05-10 11:46 UTC

**Comment by emperol2** [comment] 2022-05-10 15:13
Thank you very much for this clarification! @adamhenson
