### ISSUE TITLE
 Error: connect ECONNREFUSED 127.0.0.1:4000     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

### ISSUE THREAD

**Issue by stixaw** [foo-software/lighthouse-check-action#115] opened 2023-05-31 16:16 UTC
**Describe the bug**
While running the lighthouse report in the build I get this error:
lighthouse-check: Auditing mobile (1/1): http://chg-pde-comphealth-feature-pde-9101.s3-website-us-west-2.amazonaws.com/
lighthouse-check:
 Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:[16](https://github.com/chghealthcare/pde-ui/actions/runs/5135060033/jobs/9240179717#step:7:17)) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4000
}
Error: connect ECONNREFUSED 127.0.0.1:4000

We use
curl https://intoli.com/install-google-chrome.sh. to install google in our self-hosted runners

**To Reproduce**
- name: Install Google Chrome
        run: |
          curl https://intoli.com/install-google-chrome.sh | bash

      - name: Set Up Lighthouse Directories
        run: |
          rm -rf $LIGHTHOUSE_REPORTS_DIRECTORY
          mkdir $LIGHTHOUSE_REPORTS_DIRECTORY

      - name: Generate Lighthouse Report
        uses: foo-software/lighthouse-check-action@v9.1.0
        id: lighthouseCheck
        with:
          outputDirectory: ${{ env.LIGHTHOUSE_REPORTS_DIRECTORY }}
          urls: "http://chg-pde-comphealth-feature-${{ env.FEATURE_ID }}.s3-website-us-west-2.amazonaws.com"

**Expected behavior**
I expect this to run this was ok with Chrome 113.0.5672.126-1
**Additional context**

**Comment by adamhenson** [comment] 2023-05-31 17:13
This seems to be a duplicate of https://github.com/foo-software/lighthouse-check-action/issues/109

Please use `foo-software/lighthouse-check-action@v10.0.0`

**Closed by adamhenson** 2023-05-31 17:13 UTC
