### ISSUE TITLE
Feature request: Allow to use the host network

### ISSUE THREAD

**Issue by dlehmhus** [foo-software/lighthouse-check-action#69] opened 2021-12-01 11:06 UTC
# Feature request

## Problem
In my current setup I'm running the lighthouse-check-action against a local server (e.g. `localhost:3000`). This worked fine with v5, but since v6 all tests always score 0 points. My explanation for this is, that v6 now runs inside a docker container, and therefore by default can not access the host's network. 

## Request
Config to customize the docker container or add `--network="host"` by default.

**Comment by adamhenson** [comment] 2021-12-01 17:44
Thanks for raising this issue @dlehmhus. Your theory makes a lot of sense to me. Let me see what I can do.

**Comment by adamhenson** [comment] 2021-12-01 18:50
@dlehmhus - I'm having difficulty in coming up with a way to reproduce this. Can you provide an example?

**Comment by dlehmhus** [comment] 2021-12-02 08:26
Hey @adamhenson, here is an example [repo](https://github.com/dlehmhus/lighthouse-check-action-example/actions). It is basic create-next-app boilerplate with two feature branches, one that adds v5 and one that adds v6.

**Comment by adamhenson** [comment] 2021-12-02 16:00
Perfect, thanks @dlehmhus. I'll do some experimenting on my end. At the moment, I'm not sure if it's possible to use `--network="host"` in the `action.yml` [metadata file... using `runs`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions), but I'll do some experimenting. I'll try using [`runs.args`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsargs), but I'm not very hopeful since it's only used with `ENTRYPOINT`.

**Comment by adamhenson** [comment] 2021-12-02 20:09
The reason for converting this project to Docker was mainly because GitHub took forever in providing a Node.js runner later than 12. I was starting to doubt it would ever happen.

https://github.com/actions/runner/issues/772

But, it looks like there was a recent comment on that issue and it appears that they've released a Node 16 runner. I'm so sure the runner is available, but it appears that corresponding PR has been merged: https://github.com/actions/runner/pull/1439

I think my next step will be to confirm if Node 16 runner is actually available and then I can convert this project back to it. Perhaps we could hold on this until then.

**Comment by adamhenson** [comment] 2021-12-02 20:29
Okay, the rumors are true. Node 16 runner is now available 😅 

This PR should fix this issue once it's merged and released... hopefully within the next couple hours: https://github.com/foo-software/lighthouse-check-action/pull/71

**Comment by adamhenson** [comment] 2021-12-02 20:58
I confirmed that [v7.0.0](https://github.com/foo-software/lighthouse-check-action/pull/71) fixes this issue as reproduced in https://github.com/foo-software/lighthouse-check-action/pull/70.

Thanks again for raising this and providing a reproduction @dlehmhus.

**Closed by adamhenson** 2021-12-02 20:58 UTC
