### ISSUE TITLE
extraHeaders Set-Cookie not applyed

### ISSUE THREAD

**Issue by schoenwaldnils** [foo-software/lighthouse-check-action#93] opened 2022-05-19 13:54 UTC
This config:
```
extraHeaders: '{ "Set-Cookie": "USE_COOKIE_CONSENT_STATE={%22session%22:false}" }'
```
does not seem to be applyed. I'd exspect the `USE_COOKIE_CONSENT_STATE` cookie to be set and therfore the cookie banner not to be visible. 
But it doesn't work :/

**Comment by schoenwaldnils** [comment] 2022-05-19 14:18
Nevermind .. this way it works
```
extraHeaders: '{ "Set-Cookie": "USE_COOKIE_CONSENT_STATE={%22session%22:false}; Path=/" }'
```

**Comment by schoenwaldnils** [comment] 2022-05-20 11:59
Nevermind again :/ 
it seems the one test with the path just was a fluke. Now the cookie doesn't seem to be set and the cookie banner is shown 🤔

**Comment by adamhenson** [comment] 2022-05-20 12:22
@schoenwaldnils - this is a tested feature and is working according to tests. Please provide full detailed, simple reproduction, otherwise I'll need to close this. I would recommend a more straightforward example and proof that it's not working, otherwise it's really on you to figure out the details of your implementation.

For example, to test this feature we have configuration with [this line](https://github.com/foo-software/lighthouse-check-action/blob/master/.github/workflows/extraHeaders.yml#L22) and a [simple Express app that outputs the cookies](https://github.com/foo-software/lighthouse-check-action/blob/master/src/test/headerServer.ts), which we then see in the Lighthouse report screenshot.

We need a lot more on your side to investigate this.

I would recommend updating your code to look for a cookie that is more simple, because at the moment, I'm guessing it's the value of the cookie that's an issue (encoding decoding)... irrelevant to this project.

You should test against Lighthouse directly.

I'm going to close this for now, until you've provided a proper reproduction.

**Closed by adamhenson** 2022-05-20 12:22 UTC

**Comment by adamhenson** [comment] 2022-05-20 13:16
@schoenwaldnils - `Set-Cookie` is a response header. You cannot set it in the request unless I'm mistaken.

**Comment by adamhenson** [comment] 2022-05-20 13:17
You need to figure what the request header is that will trigger your server to respond with that response header.

**Comment by adamhenson** [comment] 2022-05-20 13:31
In summary:

I just dug through this project again and re-kicked all tests. The `extraHeaders` feature is tested in this project and I've re-kicked a fresh batch of tests and confirmed that it still works as expected. Here's how it's tested:

1. A simple Vercel Express app is deployed with every MR. [It renders cookies in the HTML](https://github.com/foo-software/lighthouse-check-action/blob/master/src/test/headerServer.ts#L24).
2. [In CI we run the latest GitHub Action code](https://github.com/foo-software/lighthouse-check-action/blob/master/.github/workflows/extraHeaders.yml#L22) against the corresponding URL above with `extraHeaders` set.
3. From the above we can confirm in the Lighthouse report screenshot that the headers exist as they were rendered in the HTML, thanks to our app established in step 1 (the Lighthouse report URL is output in CI logs... screenshot below of the most recent report).

<img width="785" alt="Screen Shot 2022-05-20 at 9 24 37 AM" src="https://user-images.githubusercontent.com/747743/169538757-07bdebaf-464c-4187-bfd3-227fcfd3c35c.png">

**Comment by adamhenson** [comment] 2022-05-20 13:34
@schoenwaldnils as I just spent a half hour of my day on this... please do your due diligence and experiment with your implementation before opening an issue in an open source project.

Contributors of open source projects volunteer time to maintain, and it's not fair for us to spend time on something that the issue opener has barely spent on. Good luck.
